export const demoUsers = [
  {
    id: "1",
    email: "admin@boxaloo.com",
    password: "admin123",
    name: "Admin User",
    role: "admin" as const,
    companyName: "BOX Platform",
  },
  {
    id: "2",
    email: "broker@example.com",
    password: "broker123",
    name: "John Smith",
    role: "broker" as const,
    companyName: "Swift Logistics LLC",
  },
  {
    id: "3",
    email: "carrier@example.com",
    password: "carrier123",
    name: "Mike Johnson",
    role: "carrier" as const,
    companyName: "Johnson Trucking",
  },
  {
    id: "4",
    email: "dispatcher@example.com",
    password: "dispatcher123",
    name: "Sarah Wilson",
    role: "dispatcher" as const,
    companyName: "Fleet Management Co",
  },
]

export const demoLoads = [
  {
    id: "LD-001",
    origin: "Chicago, IL",
    destination: "Atlanta, GA",
    pickupDate: "2024-01-15",
    deliveryDate: "2024-01-17",
    equipmentType: "Dry Van",
    weight: 45000,
    rate: 2800,
    ratePerMile: 2.1,
    distance: 717,
    commodity: "Electronics",
    broker: "Swift Logistics LLC",
    postedDate: "2024-01-10",
    status: "available" as const,
  },
  {
    id: "LD-002",
    origin: "Dallas, TX",
    destination: "Phoenix, AZ",
    pickupDate: "2024-01-16",
    deliveryDate: "2024-01-18",
    equipmentType: "Reefer",
    weight: 38000,
    rate: 1950,
    ratePerMile: 2.3,
    distance: 887,
    commodity: "Food Products",
    broker: "Reliable Freight Co",
    postedDate: "2024-01-11",
    status: "available" as const,
  },
]
